name: setsumaru1992_github_action_practice
description: setsumaru1992_github_action_practice
runs:
  using: "composite"
  steps:
    - run: echo "execute public action"
      shell: bash
    - uses: actions/checkout@v3
    # TODO: チェックアウトはこのリポジトリではなく実行元リポジトリのソースを取ってくるため、
    # カスタムアクションリポジトリのパーシャルファイルを利用する際は工夫必要
    # - run: ls -la
    # - uses: ./.github/actions/partial_action
    # - run: git log --oneline